---
kind: pipeline
type: docker
name: Build Test

steps:
  - name: build
    image: node:14-alpine
    commands:
      - npm install
      - npm run build

  - name: publish
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
      pages_directory: dist/
