image: node:lts

stages:
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm --version
  - node --version
  - npm install

pages:
  stage: deploy
  script:
    - npm install netlify-cli -g
    - npm run build
    - netlify --version
    - netfliy deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir dist/
  artifacts:
    paths:
      - dist
  only:
    - develop
