version: '3.8'

services:

  server:
    image: silkky/silkky.cloud:latest
    hostname: website
    networks:
      - traefik-public
#    logging:
#      driver: none
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"

        # Access Router
        - "traefik.http.routers.website.rule=Host(`${WEBSITE_HOSTNAME}`)"
        - "traefik.http.routers.website.tls.certresolver=letsencrypt"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.middlewares=website-headers"
        - "traefik.http.routers.website.service=website-service"
        
        # Bitwarden service
        - "traefik.http.services.website-service.loadbalancer.server.port=8080"
        - "traefik.http.services.website-service.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.website-service.loadbalancer.sticky.cookie.secure=true"

        # Headers
        - "traefik.http.middlewares.website-headers.headers.contentSecurityPolicy=default-src 'none'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: blob: https://hedgedoc.silkky.cloud; object-src 'self'; frame-src 'self'; script-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; connect-src 'self'; frame-ancestors 'self';"

networks:
  traefik-public:
    external: true