name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test the build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run build test
        run: npm run build

  deploy:
    name: Deploy to Netlify
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './dist'
          deploy-message: 'Deployment version: ${{ github.ref }}'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: true
          enable-pull-request-comment: true
          github-deployment-environment: 'Production'
          github-deployment-description: 'Production website deployed at https://demo.silkky.cloud/'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
